### ISSUE TITLE
.dll file

### ISSUE THREAD

**Issue by OGT01** [ryanries/PassFiltEx#1]
Thanks for this project!  One of the people I follow on twitter posted a link to it.  Your readme file states that we should copy the PassFiltEx.dll file to the System32 folder.  I do not see the .dll file available to download.  I should mention that I am not a programmer.

Thanks.

**Comment by OGT01** [comment]
I was able to locate the file under releases.  My apologies as I am new to GitHub.  I signed up just to view your project.  Thanks again for your work.

**Comment by ryanries** [comment]
Thanks :)

**Comment by miquelcvcvcv** [comment]
Hey, I have been programming your PasswordFilter project in order to do it better, it have more Filter charactistcs and It is configurable using regedit registers (without touching and compiling code) just changing some regedit registers. Executing your code with my visual studio work well, but at the end I just cannot make it work using windows server. I got the .etl file but I never got the expected .etl output  using Windows Message Analizer. I have also generated the .dll using only your code, but also I got the same result: no correct elt output. I just seems as PassFiltEx.dll never works for windows. Now I searching the PassFiltEx.dll file generated by ryanries in order to check if i the mistake is that I am not generating the .dll correctly or the mistake is that I do not connect the .dll correclty on windows server. Where  is the famous  and orginal PassFiltEx.dll generated by ryanries? I can not find it on github. I attach my programation anyway if it helps to find my mistake
