### ISSUE TITLE
Can you show a custom message

### ISSUE THREAD

**Issue by sheerazali19** [ryanries/PassFiltEx#19]
Can you show a custom message on password bad password default windows message shows nothing at all user might not know why is the password bad 
Ps:- just a suggestion your tool is awesome

**Comment by ryanries** [comment]
People have been seeking this for years but unfortunately it's just not feasible. The domain controller only returns a single error code when the password attempt fails due to length or complexity reasons. So the client can not actually know why the password failed. It would require a massive modification to the Windows client that would be a lot more work than just the password filter alone.

**Comment by sheerazali19** [comment]
makes sense okay
